[package]
name = "subvocal"
version = "0.1.0"
description = "Turn your notes into audio you can study by listening"
edition = "2021"

[lib]
name = "subvocal_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
